import { useEffect, useState } from 'react'
import { ArrowUpRight } from 'lucide-react'

import { loadAvailability, type Availability } from '../lib/availability'
import {
  formatPeriod,
  loadDgcisIndex,
  type DgcisIndex,
} from '../lib/dgcis'
import { usd } from '../lib/format'
import { usePageHelp } from '../lib/pagehelp'

/*
 * How to read this dashboard.
 *
 * Written because the most expensive mistake this project has made was a
 * reader - us - taking a number to mean something it did not. Every section
 * exists to stop a specific misreading that has actually happened, or was one
 * step away from happening.
 *
 * TWO RULES THIS FILE KEEPS
 *
 * Nothing is hardcoded that the data can say for itself. "543 tariff lines"
 * and "China was $700bn of the gap" were both true when they were typed and
 * both would quietly stop being true; they are read from the same files the
 * rest of the dashboard reads, so the guide ages with the data instead of
 * against it.
 *
 * Every picture is a capture of the real page, in both themes, produced by
 * qa/guide-shots.mjs. A drawing of an interface keeps looking correct long
 * after the interface has moved on.
 *
 * The captures live under /img/guide, not /guide: a folder at /guide would
 * shadow this very route, because a static-asset host resolves a directory
 * before it falls back to index.html.
 */

function Figure({
  name,
  alt,
  caption,
}: {
  name: string
  alt: string
  caption: string
}) {
  return (
    <figure className="guide-figure">
      <img
        src={`/img/guide/${name}-light.png`}
        alt={alt}
        data-shot="light"
        loading="lazy"
      />

      <img
        src={`/img/guide/${name}-dark.png`}
        alt=""
        aria-hidden="true"
        data-shot="dark"
        loading="lazy"
      />

      <figcaption>{caption}</figcaption>
    </figure>
  )
}

const CHAPTERS = [
  { id: 'what', n: 1, title: 'What this is' },
  { id: 'sources', n: 2, title: 'The two sources' },
  { id: 'levels', n: 3, title: 'The four code levels' },
  { id: 'product', n: 4, title: 'Reading a product page' },
  { id: 'line', n: 5, title: 'Reading a tariff line' },
  { id: 'blank', n: 6, title: 'Why some years are blank' },
  { id: 'around', n: 7, title: 'Finding things' },
  { id: 'out', n: 8, title: 'Taking figures out' },
  { id: 'units', n: 9, title: 'Units and periods' },
  { id: 'wrong', n: 10, title: 'If a number looks wrong' },
]

export function Guide({
  products,
  onHome,
  onOpen,
  onLines,
  onAvailability,
  onQuery,
}: {
  products: number
  onHome: () => void
  onOpen?: (code: string, level: 2 | 4 | 6) => void
  onLines: () => void
  onAvailability?: () => void
  onQuery?: () => void
}) {
  const [index, setIndex] = useState<DgcisIndex | null>(null)
  const [avail, setAvail] = useState<Availability | null>(null)

  useEffect(() => {
    let live = true

    loadDgcisIndex().then(result => {
      if (live) setIndex(result)
    })

    loadAvailability().then(result => {
      if (live) setAvail(result)
    })

    return () => {
      live = false
    }
  }, [])

  const lines = index?.lines.length ?? null
  const named = index ? index.lines.filter(line => line.title).length ?? 0 : null
  const headings = index ? new Set(index.lines.map(line => line.hs6)).size : null
  const lastPeriod = index?.periods?.last ?? null
  const biggestGap = avail?.holes?.[0] ?? null

  usePageHelp(
    () => ({
      presented: CHAPTERS.map(chapter => ({
        name: `${chapter.n}. ${chapter.title}`,
        what: '',
      })),
      facts: [
        { label: 'Chapters', value: String(CHAPTERS.length), note: 'jump from the contents list' },
        {
          label: 'Pictures',
          value: 'from the real pages',
          note: 'regenerated by qa/guide-shots.mjs, in both themes',
        },
      ],
    }),
    [],
  )

  return (
    <div className="guide-page">
      <header className="guide-head">
        <div className="eyebrow">HOW TO READ THIS DASHBOARD</div>

        <h1>The guide</h1>

        <p className="guide-lede">
          Two different measurements sit side by side here, and most of what is
          worth knowing is which one you are looking at. Ten chapters, in the
          order the questions usually arrive.
        </p>
      </header>

      <nav className="guide-toc" aria-label="Contents">
        <div className="guide-toc-label">Contents</div>

        <ol>
          {CHAPTERS.map(chapter => (
            <li key={chapter.id}>
              <a href={`#${chapter.id}`}>
                <span className="guide-toc-n">{chapter.n}</span>
                {chapter.title}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      {/* ---------------------------------------------------------- 1 */}
      <section className="guide-chapter" id="what">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">1</span>
          <h2>What this is</h2>
        </div>

        <h3>1.1 &nbsp;The question it answers</h3>

        <p>
          Who trades what, in electronics, and where India sits in it. Pick a
          product and the dashboard will tell you how big the world market is,
          who buys and sells the most of it, how much of it India buys, and
          what India&rsquo;s own customs figures say about the same goods.
        </p>

        <h3>1.2 &nbsp;What it covers</h3>

        <ul className="guide-list">
          <li>
            <strong>{products} products.</strong> Six-digit codes in the
            electronics and IT sector, as FED defines it.
          </li>
          <li>
            <strong>{lines ?? '543'} tariff lines</strong> under{' '}
            {headings ?? '255'} of those headings — India&rsquo;s own
            eight-digit detail, monthly
            {lastPeriod ? ` to ${formatPeriod(lastPeriod)}` : ''}.
          </li>
          <li>
            <strong>Both directions.</strong> What is bought and what is sold,
            everywhere the source files both.
          </li>
        </ul>

        <Figure
          name="front-page"
          alt="The HStat.India front page, with the search box and headline figures"
          caption="The front page. Search takes a product word or a code; the panels below rank what is largest and where India&rsquo;s share is biggest."
        />
      </section>

      {/* ---------------------------------------------------------- 2 */}
      <section className="guide-chapter" id="sources">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">2</span>
          <h2>The two sources</h2>
        </div>

        <p>
          Everything on this dashboard comes from one of two places. They
          measure different things, on different calendars, at different levels
          of detail. Keeping them apart is the whole job.
        </p>

        <div className="guide-two">
          <div>
            <h3>UN Comtrade</h3>

            <p>
              The world&rsquo;s trade in a six-digit product, added up across
              every economy that files with the United Nations. This is where
              the headline figures come from: world trade, India&rsquo;s share,
              who buys and who sells.
            </p>

            <ul>
              <li>Six digits — every country uses the same code.</li>
              <li>Calendar years, January to December.</li>
              <li>Complete to 2024; 2025 is patchy, 2026 is empty.</li>
              <li>US dollars.</li>
            </ul>
          </div>

          <div>
            <h3>DGCIS</h3>

            <p>
              India&rsquo;s own customs authority reporting India&rsquo;s own
              trade, at India&rsquo;s eight-digit tariff line, month by month.
              Much fresher than Comtrade, and only ever about India.
            </p>

            <ul>
              <li>Eight digits — India&rsquo;s own schedule, nobody else&rsquo;s.</li>
              <li>
                Months
                {lastPeriod ? `, currently to ${formatPeriod(lastPeriod)}` : ''}.
              </li>
              <li>Financial years, April to March, when totalled.</li>
              <li>Rupee crore and US dollar million, both as filed.</li>
            </ul>
          </div>
        </div>

        <h3>2.1 &nbsp;The word that catches people out</h3>

        <p className="guide-warn">
          <strong>&ldquo;World&rdquo; means two different things.</strong> On a
          Comtrade figure it means world trade — everyone&rsquo;s trade added
          up. On a DGCIS panel, partner &ldquo;World&rdquo; means{' '}
          <em>India trading with everywhere</em>, which is a number about
          India. The two must never be added together, and neither is a version
          of the other.
        </p>

        <h3>2.2 &nbsp;Why they are never added</h3>

        <p>
          Beyond the naming, they do not line up: different periods, different
          code levels, different reporters, and a different treatment of
          freight and insurance. A figure built from both would look fine and
          quietly mean nothing. So they are shown beside each other, always
          labelled, and never summed.
        </p>

        <Figure
          name="dgcis-panel"
          alt="India's eight-digit tariff lines shown below the world figures on a product page"
          caption="On a product page the Indian detail sits below the world figures, in its own panel, with its own source line. Same heading, different measurement."
        />
      </section>

      {/* ---------------------------------------------------------- 3 */}
      <section className="guide-chapter" id="levels">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">3</span>
          <h2>The four code levels</h2>
        </div>

        <p>
          Every product here has a Harmonised System code. The more digits, the
          narrower the thing it describes.
        </p>

        <dl className="guide-levels">
          <dt>HS-2 · chapter</dt>
          <dd>The broadest grouping. Useful for orientation, rarely for analysis.</dd>

          <dt>HS-4 · heading</dt>
          <dd>A family of related products.</dd>

          <dt>HS-6 · product</dt>
          <dd>
            The workhorse. The finest level that is comparable between
            countries, so every world figure lives here. Each of the {products}{' '}
            products has its own page.
          </dd>

          <dt>HS-8 · tariff line</dt>
          <dd>
            India&rsquo;s own subdivision of a heading, and the level customs
            actually files at.
          </dd>
        </dl>

        <h3>3.1 &nbsp;Why there is no world figure at eight digits</h3>

        <p>
          Because there is no such thing. Countries agree on the first six
          digits and write their own schedule beyond that, so India&rsquo;s{' '}
          <code>85176290</code> has no counterpart anywhere else to add up. An
          eight-digit page is always India reporting India.
        </p>

        <h3>3.2 &nbsp;How a tariff line gets its name</h3>

        <p>
          From India&rsquo;s own eight-digit schedule where the schedule has a
          name for it —{' '}
          {named !== null && lines !== null ? (
            <>
              <strong>{named} of the {lines} lines</strong> are named that way
            </>
          ) : (
            <>most lines are named that way</>
          )}
          . The rest keep their code as their name, which is how customs files
          them and how a trader quotes them. A code is unique; a borrowed word
          is not, and twenty-nine lines called &ldquo;electrical machines,
          other&rdquo; help nobody.
        </p>

        <p>
          <button className="linkish" onClick={onLines}>
            Browse every line <ArrowUpRight size={12} />
          </button>
        </p>

        <Figure
          name="tariff-index"
          alt="The tariff line index, grouped by six-digit heading"
          caption="The index groups lines under their heading, largest first, so a line is always read next to its siblings."
        />
      </section>

      {/* ---------------------------------------------------------- 4 */}
      <section className="guide-chapter" id="product">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">4</span>
          <h2>Reading a product page</h2>
        </div>

        <Figure
          name="product-top"
          alt="The top of a product page, showing world trade and India's position"
          caption="The top of a product page. World market on one side, India&rsquo;s position in it on the other; change the year and the two swap places."
        />

        <h3>4.1 &nbsp;World trade</h3>

        <p>
          Every reporting economy&rsquo;s imports from the world, added up,
          with re-imports taken out. Goods that leave a country and come back
          are already inside its import total, so summing across the world
          counts them twice. The subtraction can only ever pull the figure
          down, which means any error left runs one way: understated, never
          overstated.
        </p>

        <h3>4.2 &nbsp;India&rsquo;s position</h3>

        <p>
          India&rsquo;s own imports of the same product, its share of the world
          figure, and its rank among every reporting economy. The share is that
          Indian figure divided by that world figure — nothing is estimated
          from the other.
        </p>

        <h3>4.3 &nbsp;Who buys and who sells</h3>

        <p>
          The largest importing and exporting economies for the selected year.
          These are gross figures: re-imports are not filed partner by partner,
          so they cannot be netted at this level, and the lists will not sum to
          the headline.
        </p>

        <h3>4.4 &nbsp;What&rsquo;s inside, and coverage</h3>

        <p>
          On a chapter or heading page, what&rsquo;s inside breaks the total
          down into the product lines under it. Coverage says how much of the
          heading this dashboard actually tracks — the sector definition is
          narrower than the tariff schedule, and the difference is shown rather
          than hidden.
        </p>

        <h3>4.5 &nbsp;Tiles and the right rail</h3>

        <p>
          Every block on the page is a tile. The right-hand rail chooses which
          tiles show, what order they sit in, and builds a report from whatever
          is on screen. Hidden tiles stay hidden as you move between products.
        </p>
      </section>

      {/* ---------------------------------------------------------- 5 */}
      <section className="guide-chapter" id="line">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">5</span>
          <h2>Reading a tariff line</h2>
        </div>

        <Figure
          name="tariff-line"
          alt="The heading of a tariff line page"
          caption="A tariff line page. The name comes from India&rsquo;s schedule, the code is beside it, and the heading it belongs to is one click up."
        />

        <h3>5.1 &nbsp;The monthly series</h3>

        <p>
          Every month DGCIS has filed for this line, in the direction and unit
          selected at the top. Switching exports to imports changes every
          figure on the page; switching dollars to rupees changes the unit and
          nothing else.
        </p>

        <h3>5.2 &nbsp;Two kinds of year</h3>

        <p>
          India files financial years, April to March. Comtrade publishes
          calendar years. Both are shown, separately and labelled, because they
          are not interchangeable — and only the calendar year can be compared
          with the heading above.
        </p>

        <Figure
          name="tariff-years"
          alt="Financial-year and calendar-year totals shown separately"
          caption="Financial years and calendar years, side by side and never merged. A part year is marked as one."
        />

        <h3>5.3 &nbsp;The other lines under the same heading</h3>

        <p>
          A line means little on its own. The table at the bottom ranks every
          line under the same heading, so you can see whether you are looking
          at the whole of it or a rounding error in it.
        </p>

        <Figure
          name="siblings"
          alt="A ranked table of the other tariff lines under the same heading"
          caption="One line is often almost all of a heading. This is where you find out which."
        />
      </section>

      {/* ---------------------------------------------------------- 6 */}
      <section className="guide-chapter" id="blank">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">6</span>
          <h2>Why some years are blank</h2>
        </div>

        <h3>6.1 &nbsp;A blank is not a zero</h3>

        <p>
          A world figure is published only when enough countries have filed to
          defend it. When they have not, the year is left blank rather than
          estimated. <strong>Blank means &ldquo;we do not know&rdquo;</strong>,
          never &ldquo;nothing was traded&rdquo;.
        </p>

        <h3>6.2 &nbsp;It is usually one country</h3>

        <p>
          {biggestGap ? (
            <>
              The largest single gap right now is{' '}
              <strong>{biggestGap.reporter}</strong>, missing from{' '}
              {biggestGap.products} of these products and worth{' '}
              {usd(biggestGap.priorValue, 1)} the year before. One absent filer
              of that size is enough to make a whole year look thin.
            </>
          ) : (
            <>
              Recent years are thin mostly because of a small number of large
              absentees rather than a general collapse in reporting. One absent
              filer of that size is enough to make a whole year look thin.
            </>
          )}{' '}
          India is the exception: its own data runs months ahead, which is why
          the tariff-line panels are fresher than the world figures above them.
        </p>

        <h3>6.3 &nbsp;Checking for yourself</h3>

        <p>
          The availability page holds Comtrade&rsquo;s own record of who has
          filed what, joined to these products. It answers one question
          directly: would refreshing bring in anything new.
          {onAvailability && (
            <>
              {' '}
              <button className="linkish" onClick={onAvailability}>
                Open it <ArrowUpRight size={12} />
              </button>
            </>
          )}
        </p>

        <Figure
          name="availability"
          alt="The availability banner saying whether a refresh would bring in new data"
          caption="The banner is the answer; the tables below it are the working."
        />

        <Figure
          name="gaps"
          alt="A list of economies that have not filed, with what each was worth"
          caption="Each absence is valued at what that economy filed the year before, so you can judge how understated a figure is."
        />
      </section>

      {/* ---------------------------------------------------------- 7 */}
      <section className="guide-chapter" id="around">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">7</span>
          <h2>Finding things</h2>
        </div>

        <h3>7.1 &nbsp;Search</h3>

        <p>
          A product word (&ldquo;smartphone&rdquo;), a code at any level
          (&ldquo;8517&rdquo;, &ldquo;85176290&rdquo;), or a plain question.
          Tariff-line results appear in their own group and are never mixed
          into the world product results.
        </p>

        <h3>7.2 &nbsp;Commands</h3>

        <p>
          Type <kbd>/</kbd> in the search box for commands: jump somewhere,
          switch flow or currency, build a report, open this guide.
        </p>

        <Figure
          name="palette"
          alt="The command palette, opened by typing a slash in the search box"
          caption="One slash and the search box becomes a command list."
        />

        <h3>7.3 &nbsp;The two rails</h3>

        <ul className="guide-list">
          <li>
            <strong>The left rail is places.</strong> Home, all tariff lines,
            availability, the query builder, this guide, and whatever you have
            pinned or visited.
          </li>
          <li>
            <strong>The right rail is tools</strong> for the page in front of
            you: which tiles show, how they are arranged, and reports.
          </li>
        </ul>

        <h3>7.4 &nbsp;Links</h3>

        <p>
          Every page has an address. <code>/hs/851762</code> is a product,{' '}
          <code>/hs/85176290</code> a tariff line, and both can be sent to
          someone.
        </p>
      </section>

      {/* ---------------------------------------------------------- 8 */}
      <section className="guide-chapter" id="out">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">8</span>
          <h2>Taking figures out</h2>
        </div>

        <h3>8.1 &nbsp;The workbook</h3>

        <p>
          The download button on a product page gives you everything on it:
          annual and monthly world figures, largest importers and exporters,
          India&rsquo;s own partners, and — on its own sheet — India&rsquo;s
          tariff lines for that heading, both directions. Every Indian row
          repeats its reporter, partner and flow, because a spreadsheet gets
          sorted and forwarded and a row read alone still has to say what it
          is.
        </p>

        <h3>8.2 &nbsp;Reports</h3>

        <p>
          A report is a capture of the tiles on the page, as PDF or image, so
          what you send looks like what you read. Reports are listed on the
          front page and kept in your browser only.
        </p>

        <h3>8.3 &nbsp;Going back to the source</h3>

        <p>
          Each product page carries links that open UN Comtrade with the
          selection already made — commodity, year, flow, reporter and World as
          the partner. For anything else, the query builder composes the call
          three ways.
          {onQuery && (
            <>
              {' '}
              <button className="linkish" onClick={onQuery}>
                Open the query builder <ArrowUpRight size={12} />
              </button>
            </>
          )}
        </p>
      </section>

      {/* ---------------------------------------------------------- 9 */}
      <section className="guide-chapter" id="units">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">9</span>
          <h2>Units and periods</h2>
        </div>

        <h3>9.1 &nbsp;Money</h3>

        <p>
          Comtrade figures are US dollars. DGCIS files both rupee crore and US
          dollar million, and{' '}
          <strong>the two are never converted between each other</strong>:
          both are as published, and neither can be used to derive an exchange
          rate from the other.
        </p>

        <h3>9.2 &nbsp;Time</h3>

        <p>
          Comtrade is calendar years. DGCIS is months, totalled into Indian
          financial years running April to March. A page always says which
          basis it is on, and a part year is marked as a part year.
        </p>

        <h3>9.3 &nbsp;Provisional</h3>

        <p>
          A year marked provisional is published but still filling in: some
          economies that filed last year have not filed this one yet. The
          figure is real and it is going to move up.
        </p>
      </section>

      {/* --------------------------------------------------------- 10 */}
      <section className="guide-chapter" id="wrong">
        <div className="guide-chapter-head">
          <span className="guide-chapter-n">10</span>
          <h2>If a number looks wrong</h2>
        </div>

        <p>Check three things, in this order.</p>

        <ol className="guide-check">
          <li>
            <strong>Which source?</strong> Comtrade is the world; DGCIS is
            India. Every panel says which.
          </li>
          <li>
            <strong>Which direction?</strong> Imports and exports of the same
            goods are different numbers, and the switch is at the top of the
            page.
          </li>
          <li>
            <strong>Which period basis?</strong> A financial year and a
            calendar year that share a number are not the same twelve months.
          </li>
        </ol>

        <p className="guide-warn">
          Almost every surprise on this dashboard turns out to be one of those
          three. The one that caught us hardest was a flow label reading
          &ldquo;imports&rdquo; over data that was exports — which is why the
          pipeline now refuses to write a file whose flow it cannot verify
          against an outside measurement.
        </p>

        {onOpen && (
          <p>
            <button className="linkish" onClick={() => onOpen('854231', 6)}>
              Try it on a product page <ArrowUpRight size={12} />
            </button>
          </p>
        )}
      </section>

      <button className="linkish guide-home" onClick={onHome}>
        Back to the front page
      </button>
    </div>
  )
}
