/*
 * The guide's screenshots, captured from the dashboard itself.
 *
 * A guide illustrated with drawings goes stale quietly: the drawing keeps
 * looking right long after the thing it describes has changed. These are
 * captures of the real pages, in both themes, regenerated by running this
 * script - so when a panel moves, the picture of it moves too, and nobody has
 * to notice.
 *
 *   npm run build
 *   node qa/suite/serve.mjs dist 4178 &
 *   node qa/guide-shots.mjs
 *
 * Output: public/img/guide/<name>-<theme>.png, which the build copies as-is.
 *
 * NOT public/guide. A folder there would sit at /guide, which is a route, and
 * a static-asset host resolves the directory before it reaches the SPA
 * fallback - so the guide page would 404 in production while looking fine in
 * dev. Keep these out of the route namespace.
 *
 * Captured at 1.5x rather than 2x. These are committed to the repository, and
 * a guide is not worth three megabytes of it; 1.5 is still crisp on a retina
 * screen at the width they are displayed. No image library is used on purpose
 * - the suite already refuses to put playwright in package.json, and a
 * screenshot script is not a reason to add a native dependency either.
 */
import { chromium } from 'playwright'
import { mkdirSync } from 'node:fs'

const base = process.env.BASE || 'http://127.0.0.1:4178'
const out = 'public/img/guide'

/* Each shot is a selector on a page, cropped to the thing being explained.
 * Width is deliberately modest: these sit inside a column of prose, and a
 * 1440px capture shrunk into 640 is unreadable. */
const SHOTS = [
  { name: 'front-page',  path: '/',              sel: '.home-hero',        width: 900, clipH: 400 },
  { name: 'product-top', path: '/hs/854231',     sel: '.tiledeck',         width: 1100, clipH: 560 },
  { name: 'dgcis-panel', path: '/hs/854231',     sel: '.dgcis-table-wrap', width: 1100 },
  { name: 'tariff-line', path: '/hs/85176290',   sel: '.hs8-head',         width: 900 },
  { name: 'tariff-years',path: '/hs/85176290',   sel: '.hs8-years',        width: 1000 },
  { name: 'siblings',    path: '/hs/85176290',   sel: '.hs8-siblings',     width: 1000, clipH: 420 },
  { name: 'availability',path: '/availability',  sel: '.avail-verdict',    width: 900 },
  { name: 'gaps',        path: '/availability',  sel: '.avail-holes',      width: 900, clipH: 340 },
  { name: 'tariff-index',path: '/tariff-lines',  sel: '.lines-group',      width: 1000 },
  { name: 'palette',     path: '/',              sel: '.search-hub',       width: 800, clipH: 420, type: '/' },
]

mkdirSync(out, { recursive: true })

const browser = await chromium.launch()
let made = 0

for (const shot of SHOTS) {
  for (const theme of ['light', 'dark']) {
    const page = await browser.newPage({
      viewport: { width: shot.width + 340, height: 1100 },
      deviceScaleFactor: 1.5,
    })

    await page.goto(base + shot.path, { waitUntil: 'networkidle' })
    await page.evaluate(t => { document.documentElement.dataset.theme = t }, theme)

    /* The rail is chrome, not content, and it is explained in its own
     * section. Collapsing it keeps every capture to the page itself. */
    await page.evaluate(() => { document.documentElement.dataset.nav = 'icons' })
    await page.waitForTimeout(900)

    if (shot.type) {
      const input = await page.$('.search-hub input')
      if (input) { await input.click(); await input.type(shot.type); await page.waitForTimeout(500) }
    }

    const el = await page.$(shot.sel)

    if (!el) {
      console.log('MISSING', shot.name, shot.sel)
      await page.close()
      continue
    }

    /* page.screenshot({clip}) works in page coordinates and does not scroll,
     * so anything below the fold has to be brought into view first. */
    await el.scrollIntoViewIfNeeded()
    await page.waitForTimeout(250)

    const box = await el.boundingBox()
    const clip = shot.clipH && box
      ? { x: box.x, y: box.y, width: box.width, height: Math.min(box.height, shot.clipH) }
      : undefined

    const file = `${out}/${shot.name}-${theme}.png`

    if (clip) await page.screenshot({ path: file, clip })
    else await el.screenshot({ path: file })

    made += 1
    await page.close()
  }
}

await browser.close()
console.log(`${made} captures written to ${out}`)
